version: "3.9"
services:
  db:
    image: arm64v8/postgres:15-alpine
    # container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: postpres-db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5454:5432"
    volumes:
      - /var/postgressql:/var/lib/postgresql/data
# docker compose -p postgres-my-nestjs up --build